/* Novice anaesthetist syllabus — content data.
 *
 * Every e-LfH link below was checked against the live e-LfH catalogue on 2026-09-23
 * (see SOURCES.md S3). RCoA facts come from the IAC Workbook v1.2 (S4) and the RCoA
 * Novice Guide (S1). The syllabus structure and teaching approach are adapted, with
 * permission, from Dr Alistair Brooks's "An Introduction to Anaesthesia" (S2).
 *
 * Session IDs are e-LfH "Component/Details" IDs, which are public pages that do not
 * need a login to view (a login is needed to launch the session itself).
 */

const ELFH = id => `https://portal.e-lfh.org.uk/Component/Details/${id}`;
const CAT = h => `https://portal.e-lfh.org.uk/Catalogue/Index?HierarchyId=${h}&programmeId=14`;

window.SITE = {
  checked: '23 September 2026',

  links: {
    elfhRegister: 'https://portal.e-lfh.org.uk/Register',
    elfhModule1: ELFH(452316),
    elfhModule1Catalogue: CAT('0_14_37596_9983'),
    elfhBasicSciences: CAT('0_14_34064'),
    rcoaNoviceGuide: 'https://www.rcoa.ac.uk/documents/novice-guide',
    rcoaNoviceCurriculum: 'https://www.rcoa.ac.uk/documents/novice-guide/curriculum',
    rcoaNoviceElearning: 'https://www.rcoa.ac.uk/documents/novice-guide/e-learning',
    rcoaTypicalDay: 'https://www.rcoa.ac.uk/documents/novice-guide/typical-day-novice',
    rcoaLLP: 'https://www.rcoa.ac.uk/documents/novice-guide/lifelong-learning-platform',
    rcoaWellbeing: 'https://www.rcoa.ac.uk/documents/novice-guide/wellbeing-support',
    rcoaKeyContacts: 'https://www.rcoa.ac.uk/documents/novice-guide/key-contacts-training',
    rcoaFaqs: 'https://www.rcoa.ac.uk/documents/novice-guide/faqs',
    iacWorkbook: 'https://www.rcoa.ac.uk/sites/default/files/documents/2022-09/EPA-1-2-2022%20v1.2.pdf',
    ela1Workbook: 'https://www.rcoa.ac.uk/media/10031',
    qrh: 'https://anaesthetists.org/Home/Resources-publications/Safety-alerts/Anaesthesia-emergencies/Quick-Reference-Handbook',
    das: 'https://das.uk.com/guidelines',
    resus: 'https://www.resus.org.uk/professional-library/2025-resuscitation-guidelines',
    yhSchool: 'https://www.yorksandhumberdeanery.nhs.uk/anaesthesia',
    yhInduction: 'https://www.yorksandhumberdeanery.nhs.uk/anaesthesia/school-information/induction',
    yhSourcesOfHelp: 'https://www.yorksandhumberdeanery.nhs.uk/anaesthesia/school-information/sources-help',
    yairn: 'https://yairn.co.uk/',
  },

  /* e-LfH resources, keyed by session code. [title, url] */
  ela: {
    // e-LA Module 01 — Introduction to Clinical Anaesthesia (current live structure)
    '01_01_01': ['The anaesthetist and the theatre team', ELFH(451535)],
    '01_01_02': ['Preparation and usage of equipment and drugs', ELFH(451546)],
    '01_01_03': ['General theatre conduct', ELFH(451767)],
    '01_01_04': ['Medicines safety in anaesthetic practice', ELFH(638463)],
    '01_06_01': ['Gases and vapours', ELFH(845343)],
    '01_06_02': ['Medical gas supplies', ELFH(451016)],
    '01_06_03': ['Gas and vapour controls', ELFH(452384)],
    '01_06_04': ['Breathing system components', ELFH(452418)],
    '01_06_05': ['Common breathing systems', ELFH(452442)],
    '01_06_06': ['Principles of IPPV', ELFH(452476)],
    '01_06_08': ['Filters, humidifiers and scavenging systems', ELFH(452372)],
    '01_07_01': ['Basic monitoring: ECG, SpO2 and blood pressure', ELFH(452534)],
    '01_07_02': ['Gas monitoring: O2, CO2 and anaesthetic agents', ELFH(452390)],
    '01_07_03': ['Nerve stimulators and temperature monitoring', ELFH(451523)],
    '01_08_01': ['Checking the anaesthetic machine', ELFH(451918)],
    '01_08_02': ['Checking other anaesthetic equipment', ELFH(452460)],
    '01_08_03': ['Common equipment problems', ELFH(452504)],
    '01_09_01': ['General preoperative measures', ELFH(451552)],
    '01_09_02': ['The purpose of preoperative visiting', ELFH(451588)],
    '01_09_03': ['History and examination', ELFH(451179)],
    '01_09_04': ['Prediction of a difficult airway', ELFH(452731)],
    '01_09_05': ['ASA grading and preoperative investigations', ELFH(452401)],
    '01_09_06': ['Risk and consent', ELFH(454104)],
    '01_10_01': ['Higher risk groups: cardiovascular and respiratory disease', ELFH(451963)],
    '01_10_02': ['Higher risk groups: other miscellaneous conditions', ELFH(451974)],
    '01_10_03': ['Higher risk groups: extremes of age and emergency surgery', ELFH(452010)],
    '01_11_01': ['Aims of anaesthesia', ELFH(451564)],
    '01_11_02': ['Sedation', ELFH(451570)],
    '01_11_03': ['Local/regional anaesthesia', ELFH(451576)],
    '01_12_01': ['Airway maintenance: facemask', ELFH(451348)],
    '01_12_02': ['Airway maintenance: cLMA', ELFH(451374)],
    '01_12_03': ['Airway maintenance: tracheal tube 1', ELFH(451308)],
    '01_12_04': ['Airway maintenance: tracheal tube 2', ELFH(451320)],
    '01_12_05': ['Airway obstruction', ELFH(451511)],
    '01_12_06': ['Management of failed intubation', ELFH(451326)],
    '01_13_01': ['Venous access', ELFH(452695)],
    '01_13_02': ['Choice of airway', ELFH(451669)],
    '01_13_03': ['Pre-oxygenation', ELFH(451314)],
    '01_13_04': ['Intravenous induction sequence', ELFH(451332)],
    '01_13_05': ['Stages of unconsciousness', ELFH(451651)],
    '01_14_01': ['GA: spontaneous ventilation with an LMA', ELFH(451390)],
    '01_14_02': ['GA: ventilation with an ETT', ELFH(451396)],
    '01_14_03': ['Rapid sequence induction', ELFH(451402)],
    '01_15_01': ['Maintenance of anaesthesia and avoiding awareness', ELFH(452034)],
    '01_15_02': ['Practical examples of drugs used during maintenance', ELFH(452091)],
    '02_01_28': ['Overview of intravenous fluids', ELFH(777691)],
    '01_15_04': ['Ventilation during maintenance: spontaneous or mechanical', ELFH(452131)],
    '01_15_05': ['Monitoring, vigilance and patient positioning', ELFH(452149)],
    '01_15_06': ['Haemorrhage and hypovolaemia', ELFH(452177)],
    '01_16_01': ['Reversal and extubation', ELFH(451617)],
    '01_16_02': ['Management of slow and failed recovery', ELFH(452022)],
    '01_16_03': ['Transferring the patient to recovery', ELFH(451611)],
    '01_17_02': ['Airway maintenance and oxygen therapy', ELFH(451841)],
    '01_17_03': ['Postoperative pain and vomiting', ELFH(451594)],
    '01_17_04': ['Ward visit after major surgery', ELFH(451600)],
    '01_18_01': ['Respiratory problems', ELFH(451582)],
    '01_18_02': ['Cardiovascular problems', ELFH(452293)],
    '01_18_03': ['Anaphylaxis', ELFH(452171)],
    '01_19_01': ['Principles of advanced life support', ELFH(452546)],
    '01_32_01': ['Module 1 self-assessment 1: physiology', ELFH(451126)],
    '01_32_02': ['Module 1 self-assessment 2: pharmacology', ELFH(451200)],
    '01_32_03': ['Module 1 self-assessment 3: equipment', ELFH(451206)],
    '01_32_04': ['Module 1 self-assessment 4: anaesthetics', ELFH(451924)],

    // e-LA Core Training — Basic Sciences (Modules 07a–07e). Module 1's own basic
    // science sessions (01_02 to 01_05) have been retired, so these replace them.
    '07b_02_07': ['Central and autonomic regulation of cardiac function', ELFH(561606)],
    '07b_02_09': ['Control of cardiac output', ELFH(561790)],
    '07b_02_10': ['Control of systemic blood pressure', ELFH(561591)],
    '07b_03_01': ['Gaseous exchange: oxygen', ELFH(561455)],
    '07b_03_04': ['Function of haemoglobin in oxygen carriage', ELFH(561631)],
    '07b_03_06': ['Pulmonary ventilation: volumes, flows, dead space and preoxygenation', ELFH(561364)],
    '07b_03_07': ['Ventilation/perfusion abnormalities', ELFH(561374)],
    '07b_03_08': ['Mechanics of ventilation and the effect of IPPV on the lungs', ELFH(561851)],
    '07b_03_10': ['Ventilatory failure and oxygen therapy', ELFH(562478)],
    '07b_04_07': ['Autonomic nervous system', ELFH(561521)],
    '07c_03_01': ['Halogenated volatile agents', ELFH(692054)],
    '07c_03_02': ['Nitrous oxide and xenon', ELFH(693258)],
    '07c_04_02': ['Propofol', ELFH(692196)],
    '07c_04_06': ['Properties of an ideal intravenous induction agent', ELFH(692516)],
    '07c_05_01': ['Local anaesthetic agents', ELFH(692088)],
    '07c_05_02': ['Simple analgesia: aspirin and paracetamol', ELFH(693247)],
    '07c_05_03': ['Non-steroidal anti-inflammatory drugs (NSAIDs)', ELFH(693787)],
    '07c_05_04': ['Opioid drugs: general properties', ELFH(692063)],
    '07c_05_05': ['Morphine and other opioids', ELFH(692567)],
    '07c_06_01': ['The neuromuscular junction and the nicotinic ACh receptor', ELFH(692128)],
    '07c_06_03': ['Non-depolarising muscle relaxants: general properties', ELFH(692562)],
    '07c_06_06': ['Reversal of neuromuscular blockade', ELFH(692270)],
    '07c_07_02': ['Drugs and the sympathetic nervous system', ELFH(692108)],
    '07c_07_06': ['Inotropes and vasoconstrictors', ELFH(692113)],
    '07c_09_02': ['Antiemetic drugs', ELFH(714053)],
    '07e_01_02': ['Gas cylinders', ELFH(417102)],
    '07e_02_02': ['Vaporisers, oxygen flush and alarms', ELFH(417602)],
    '07e_03_02': ['Circle system', ELFH(417817)],
    '07e_04_01': ['Face masks and oxygen delivery devices', ELFH(417751)],
    '07e_04_04': ['Laryngoscopes and intubation aids', ELFH(417932)],
    '07e_04_05': ['Tracheal tubes', ELFH(417942)],
    '07e_07_02': ['Electrocardiogram (ECG)', ELFH(418395)],
    '07e_07_03': ['Pulse oximetry', ELFH(418725)],
    '07e_07_04': ['Capnography', ELFH(419277)],
    '07e_07_05': ['Non-invasive blood pressure measurement', ELFH(419339)],
    '07e_07_08': ['Monitoring of neuromuscular conduction', ELFH(419177)],
    '07e_08_01': ['Oxygen concentration analysers', ELFH(417280)],

    // Whole catalogue sections, where no single session fits
    'cat-07a-headneck': ['07a Anatomy: head and neck (section)', CAT('0_14_34064_8727_62369')],
    'cat-07a-thorax': ['07a Anatomy: thorax (section)', CAT('0_14_34064_8727_62370')],
    'cat-07a-heart': ['07a Anatomy: heart (section)', CAT('0_14_34064_8727_62371')],
    'cat-07c-induction': ['07c Pharmacology: intravenous induction agents (section)', CAT('0_14_34064_9558_52081')],
    'cat-07e-infection': ['07e Equipment: equipment to prevent cross infection (section)', CAT('0_14_34064_8730_31254')],
    'cat-07e-electrical': ['07e Equipment: electrical safety (section)', CAT('0_14_34064_8730_31255')],
  },

  /* IAC Key Capability clusters (RCoA IAC Workbook v1.2, 2022). */
  clusters: {
    epa1: { short: 'EPA 1', name: 'EPA 1: Pre-operative assessment' },
    pre: { short: 'Pre-op', name: 'EPA 2: Pre-operative preparation' },
    intra: { short: 'Intra-op', name: 'EPA 2: Intra-operative care' },
    post: { short: 'Post-op', name: 'EPA 2: Post-operative care' },
    emerg: { short: 'Emergencies', name: 'EPA 2: Managing emergencies and simulation' },
  },

  /* Syllabus, following Dr Brooks's structure (domain > group > topic).
   * first: true marks the topics that come up in his two descriptions of a GA,
   * which is where he suggests a novice starts. */
  domains: [
    {
      id: 'basic', name: 'Basic sciences',
      groups: [
        { name: 'Anatomy', topics: [
          { id: 'anat-airway', title: 'Anatomy of the airway', first: true, iac: ['intra'], ela: ['cat-07a-headneck'],
            note: 'Everything about mask ventilation, supraglottic airways and laryngoscopy builds on this.' },
          { id: 'anat-resp', title: 'The lungs and respiratory system', iac: [], ela: ['cat-07a-thorax'] },
          { id: 'anat-heart', title: 'The heart and major vessels', iac: [], ela: ['cat-07a-heart'] },
        ]},
        { name: 'Physiology', topics: [
          { id: 'phys-cvs', title: 'Cardiovascular physiology and the determinants of blood pressure', first: true, iac: ['intra'],
            ela: ['07b_02_09', '07b_02_10'],
            note: 'MAP = CO × SVR and CO = HR × SV. Use these to work out why induction drops the blood pressure and what to do about it.' },
          { id: 'phys-o2', title: 'Oxygen transport, consumption and the physiology of apnoea', first: true, iac: ['intra'],
            ela: ['07b_03_01', '07b_03_04', '07b_03_06'],
            note: 'Oxygen delivery = CO × Hb × SpO2 × 1.39. How long an apnoeic patient takes to desaturate depends on FRC, the oxygen fraction within it, and metabolic rate.' },
          { id: 'phys-resp', title: 'Respiratory physiology and ventilation', iac: ['intra'], ela: ['07b_03_06', '07b_03_08', '07b_03_07'] },
          { id: 'phys-nmj', title: 'The neuromuscular junction', iac: [], ela: ['07c_06_01'] },
          { id: 'phys-ans', title: 'The autonomic nervous system', iac: [], ela: ['07b_04_07', '07b_02_07'] },
          { id: 'phys-ga', title: 'Physiological effects of general anaesthesia', iac: ['intra'], ela: ['01_13_05', '07b_03_08'],
            note: 'IAC key capability: understands the physiological effects of general anaesthesia.' },
        ]},
        { name: 'Pharmacology', topics: [
          { id: 'ph-induction', title: 'Intravenous induction agents', first: true, iac: ['pre'], ela: ['07c_04_02', '07c_04_06', 'cat-07c-induction'] },
          { id: 'ph-volatile', title: 'Inhalational anaesthetic agents', first: true, iac: ['pre'], ela: ['07c_03_01', '07c_03_02'] },
          { id: 'ph-analgesia', title: 'Perioperative analgesia', first: true, iac: ['pre', 'post'], ela: ['07c_05_02', '07c_05_03', '07c_05_04', '07c_05_05'] },
          { id: 'ph-nmb', title: 'Muscle relaxants and their reversal', iac: ['pre'], ela: ['07c_06_03', '07c_06_06'] },
          { id: 'ph-vaso', title: 'Vasoactive and emergency drugs (sympathomimetics, anticholinergics)', first: true, iac: ['pre'],
            ela: ['07c_07_02', '07c_07_06'],
            note: 'Know what is drawn up before every case and why.' },
          { id: 'ph-antiemetic', title: 'Antiemetics', first: true, iac: ['pre'], ela: ['07c_09_02'] },
          { id: 'ph-la', title: 'Local anaesthetic agents', iac: [], ela: ['07c_05_01'] },
          { id: 'ph-fluids', title: 'Intravenous fluids', iac: ['intra'], ela: ['02_01_28'] },
          { id: 'ph-safety', title: 'Medicines safety', iac: ['pre'], ela: ['01_01_04'],
            note: 'Flush the cannula straight after every bolus. Undelivered drug left in the dead space can reach the patient later, in recovery or on the ward.' },
        ]},
        { name: 'Physics, measurement and equipment', topics: [
          { id: 'eq-check', title: 'Checking the anaesthetic machine and other equipment', first: true, iac: ['pre'],
            ela: ['01_08_01', '01_08_02', '01_08_03'] },
          { id: 'eq-gases', title: 'Gases, vapours and medical gas supplies', iac: ['pre'], ela: ['01_06_01', '01_06_02', '07e_01_02'] },
          { id: 'eq-controls', title: 'Gas and vapour controls', iac: ['pre'], ela: ['01_06_03', '07e_02_02'] },
          { id: 'eq-breathing', title: 'Breathing systems, filters and scavenging', iac: ['pre'], ela: ['01_06_04', '01_06_05', '07e_03_02', '01_06_08'] },
          { id: 'eq-ippv', title: 'Principles of IPPV, ventilator settings and alarms', iac: ['intra'], ela: ['01_06_06', '07b_03_08'] },
          { id: 'eq-monitoring', title: 'Basic monitoring: ECG, SpO2 and blood pressure', first: true, iac: ['pre', 'intra'],
            ela: ['01_07_01', '07e_07_02', '07e_07_03', '07e_07_05'],
            note: 'Our monitors are surrogates. Nothing on the screen measures consciousness or oxygen delivery to the brain directly.' },
          { id: 'eq-gasmon', title: 'Gas monitoring: O2, CO2 and anaesthetic agents', first: true, iac: ['pre', 'intra'],
            ela: ['01_07_02', '07e_07_04', '07e_08_01'] },
          { id: 'eq-nmt', title: 'Nerve stimulators and temperature monitoring', iac: ['intra'], ela: ['01_07_03', '07e_07_08'] },
          { id: 'eq-electrical', title: 'Electrical safety', iac: [], ela: ['cat-07e-electrical'] },
        ]},
      ],
    },
    {
      id: 'medsurg', name: 'Medicine and surgery',
      groups: [
        { name: 'Co-morbidity and risk', topics: [
          { id: 'ms-cvsresp', title: 'Cardiovascular and respiratory disease', iac: ['epa1'], ela: ['01_10_01'],
            note: 'The IAC asks you to recognise severe co-morbidity (ASA III or above) and tell a senior. It does not expect you to optimise it.' },
          { id: 'ms-other', title: 'Other co-morbidities: obesity, diabetes, renal disease, coagulation', iac: ['epa1'], ela: ['01_10_02'] },
          { id: 'ms-highrisk', title: 'Extremes of age and emergency surgery', iac: ['epa1'], ela: ['01_10_03'] },
          { id: 'ms-critical', title: 'Recognising critical illness in the surgical patient', iac: ['epa1', 'emerg'], ela: ['01_10_03', '01_15_06'] },
          { id: 'ms-data', title: 'Interpreting investigations: ECG, bloods, blood gases, chest X-ray', iac: ['epa1'], ela: ['01_09_05'],
            note: 'Module 1 has no dedicated session on this. Cover it through case-based discussion with your supervisor.' },
        ]},
      ],
    },
    {
      id: 'generic', name: 'Generic anaesthesia',
      groups: [
        { name: 'Principles', topics: [
          { id: 'g-aims', title: 'Aims of anaesthesia', first: true, iac: [], ela: ['01_11_01'],
            note: 'Dr Brooks puts it in two parts: facilitate the operation, and maintain acceptable (not normal) physiology.' },
          { id: 'g-team', title: 'The anaesthetist, the theatre team and the WHO checklist', first: true, iac: ['pre'], ela: ['01_01_01', '01_01_03'] },
          { id: 'g-prep', title: 'Preparing equipment and drugs', first: true, iac: ['pre'], ela: ['01_01_02'] },
          { id: 'g-techniques', title: 'The two basic techniques: spontaneous ventilation via LMA, and IPPV via ETT', first: true, iac: ['intra'],
            ela: ['01_14_01', '01_14_02'] },
          { id: 'g-scope', title: 'Your scope of practice, and when to call for help', iac: ['epa1', 'pre', 'emerg'], ela: [],
            links: [['RCoA Novice Guide: a typical day as a novice', 'rcoaTypicalDay']],
            note: 'This appears in both EPAs. Know who your supervisor is and how to reach them, for every list.' },
        ]},
        { name: 'Pre-operative assessment', topics: [
          { id: 'g-visit', title: 'The purpose of the pre-operative visit', first: true, iac: ['epa1'], ela: ['01_09_02'] },
          { id: 'g-history', title: 'History and examination', first: true, iac: ['epa1'], ela: ['01_09_03'],
            note: 'Always history, then examination, then investigations, in that order.' },
          { id: 'g-airway', title: 'Predicting a difficult airway', iac: ['epa1'], ela: ['01_09_04'] },
          { id: 'g-fasting', title: 'Fasting and general pre-operative measures', iac: ['pre'], ela: ['01_09_01'] },
          { id: 'g-asa', title: 'ASA grading and pre-operative investigations', iac: ['epa1'], ela: ['01_09_05'] },
          { id: 'g-consent', title: 'Explaining the plan, risk and consent', iac: ['epa1'], ela: ['01_09_06'] },
        ]},
        { name: 'Induction', topics: [
          { id: 'g-iv', title: 'Venous access', first: true, iac: ['intra'], ela: ['01_13_01'] },
          { id: 'g-preox', title: 'Pre-oxygenation', first: true, iac: ['intra'], ela: ['01_13_03', '07b_03_06'] },
          { id: 'g-ivind', title: 'The intravenous induction sequence and its common problems', first: true, iac: ['intra'], ela: ['01_13_04'] },
          { id: 'g-stages', title: 'Stages of unconsciousness', first: true, iac: ['intra'], ela: ['01_13_05'] },
          { id: 'g-rsi', title: 'Rapid sequence induction', iac: ['intra'], ela: ['01_14_03'] },
          { id: 'g-position', title: 'Transfer to theatre and positioning for surgery', iac: ['intra'], ela: ['01_15_05'],
            note: 'The IAC asks specifically about pressure areas, peripheral nerves and other delicate structures.' },
        ]},
        { name: 'Airway management', topics: [
          { id: 'a-mask', title: 'Facemask and bag-mask ventilation', first: true, iac: ['intra'], ela: ['01_12_01', '07e_04_01'],
            note: 'Practise one-handed mask ventilation with both hands. Ask to hold a mask for a whole case.' },
          { id: 'a-sad', title: 'Supraglottic airways (LMA) and choosing an airway', first: true, iac: ['intra'], ela: ['01_12_02', '01_13_02'] },
          { id: 'a-tube', title: 'Tracheal intubation: direct and video laryngoscopy', iac: ['intra'], ela: ['01_12_03', '01_12_04', '07e_04_04', '07e_04_05'] },
          { id: 'a-obstruction', title: 'Airway obstruction and laryngospasm', iac: ['intra', 'emerg'], ela: ['01_12_05'] },
          { id: 'a-failed', title: 'Failed intubation and the DAS algorithm', iac: ['emerg'], ela: ['01_12_06'],
            links: [['Difficult Airway Society guidelines (2025 adult guideline)', 'das']],
            note: 'For the IAC you must demonstrate the failed intubation routine on a manikin.' },
        ]},
        { name: 'Maintenance', topics: [
          { id: 'm-maint', title: 'Maintenance of anaesthesia and avoiding awareness', first: true, iac: ['intra'], ela: ['01_15_01'] },
          { id: 'm-drugs', title: 'Drugs used during maintenance', first: true, iac: ['intra'], ela: ['01_15_02'] },
          { id: 'm-vent', title: 'Spontaneous and controlled ventilation', iac: ['intra'], ela: ['01_15_04'] },
          { id: 'm-vigilance', title: 'Monitoring and vigilance for untoward events', first: true, iac: ['intra'], ela: ['01_15_05'] },
          { id: 'm-fluids', title: 'Intravenous fluid therapy', first: true, iac: ['intra'], ela: ['02_01_28'] },
          { id: 'm-bleeding', title: 'Haemorrhage and hypovolaemia', iac: ['intra'], ela: ['01_15_06'] },
          { id: 'm-infection', title: 'Infection prevention and control in theatre', iac: ['intra'], ela: ['cat-07e-infection'] },
        ]},
        { name: 'Emergence and recovery', topics: [
          { id: 'e-extubation', title: 'Reversal and extubation', iac: ['intra'], ela: ['01_16_01'] },
          { id: 'e-slow', title: 'Slow and failed recovery', iac: ['post'], ela: ['01_16_02'] },
          { id: 'e-transfer', title: 'Transfer and handover to recovery', first: true, iac: ['post'], ela: ['01_16_03'] },
          { id: 'e-oxygen', title: 'Airway and oxygen therapy in recovery', iac: ['post'], ela: ['01_17_02', '07b_03_10'] },
          { id: 'e-pain', title: 'Post-operative pain (including PCA and rescue opioids) and PONV', first: true, iac: ['post'], ela: ['01_17_03'] },
          { id: 'e-ward', title: 'The post-operative ward visit', iac: ['post'], ela: ['01_17_04'] },
        ]},
        { name: 'Other techniques', topics: [
          { id: 'o-sedation', title: 'Sedation', iac: [], ela: ['01_11_02'] },
          { id: 'o-regional', title: 'Local and regional anaesthesia', iac: [], ela: ['01_11_03'] },
        ]},
      ],
    },
    {
      id: 'complications', name: 'Critical incidents and emergencies',
      groups: [
        { name: 'Critical incidents', topics: [
          { id: 'c-resp', title: 'Respiratory critical incidents', iac: ['emerg'], ela: ['01_18_01'] },
          { id: 'c-cvs', title: 'Cardiovascular critical incidents', iac: ['emerg'], ela: ['01_18_02'] },
          { id: 'c-anaphylaxis', title: 'Anaphylaxis', iac: ['emerg'], ela: ['01_18_03'] },
          { id: 'c-qrh', title: 'The Quick Reference Handbook and "unknown" emergencies', iac: ['emerg'], ela: [],
            links: [['Association of Anaesthetists Quick Reference Handbook', 'qrh']],
            note: 'The IAC asks you to discuss and rehearse the QRH "unknowns" in simulation.' },
          { id: 'c-nts', title: 'Human factors and non-technical skills', iac: ['emerg'], ela: ['01_01_01'] },
          { id: 'c-als', title: 'Adult advanced life support', iac: ['emerg'], ela: ['01_19_01'],
            links: [['Resuscitation Council UK 2025 guidelines', 'resus']] },
        ]},
        { name: 'Check yourself', topics: [
          { id: 'x-selftest', title: 'e-LA Module 1 self-assessments', iac: [], ela: ['01_32_01', '01_32_02', '01_32_03', '01_32_04'] },
        ]},
      ],
    },
  ],

  /* Dr Brooks's two descriptions of a GA (Section 3), condensed into stages.
   * Example: fit 21-year-old, knee arthroscopy, propofol + fentanyl, sevoflurane,
   * spontaneous ventilation via LMA. */
  journey: [
    { id: 'before', title: 'Before the patient arrives',
      points: [
        'Assess the patient: history, examination, investigations, then make a plan.',
        'Explain, discuss risks, take consent, answer questions. Discuss with your consultant.',
        'Check the anaesthetic machine and draw up emergency drugs.',
        'Take part in the team brief: names, roles, the plan for the list, concerns.',
      ],
      topics: ['g-visit', 'g-history', 'g-consent', 'eq-check', 'ph-vaso', 'g-team'] },
    { id: 'signin', title: 'Sign in',
      points: [
        'Handover from ward staff, and the WHO checklist sign-in.',
        'Apply minimum monitoring properly: right cuff size, electrodes in the right place. It is your monitoring.',
        'Gain IV access and flush it.',
      ],
      topics: ['g-team', 'eq-monitoring', 'g-iv', 'ph-safety'] },
    { id: 'induction', title: 'Induction',
      points: [
        'Pre-oxygenate (until you know the arguments, do it for everyone).',
        'Induction and co-induction agents cause loss of consciousness, loss of airway tone, apnoea and a fall in blood pressure.',
        'Mitigate each one: open the airway, ventilate by bag and mask, and treat hypotension if needed.',
        'Turn on the volatile, place the LMA, and ventilate until spontaneous breathing returns.',
      ],
      topics: ['g-preox', 'phys-o2', 'ph-induction', 'g-ivind', 'a-mask', 'phys-cvs', 'ph-volatile', 'a-sad'] },
    { id: 'maintenance', title: 'Maintenance',
      points: [
        'On arrival in theatre, recheck airway, breathing and circulation. Assume anything could have gone wrong.',
        'Time out, then the surgical stimulus: watch the breathing, heart rate and blood pressure respond.',
        'Stay by the patient and watch. In your first weeks, leave the anaesthetic record to your supervisor.',
        'Carry out your plans for fluids, analgesia and antiemesis before emergence.',
      ],
      topics: ['m-vigilance', 'eq-gasmon', 'm-maint', 'm-drugs', 'm-fluids', 'ph-analgesia', 'ph-antiemetic'] },
    { id: 'emergence', title: 'Emergence and recovery',
      points: [
        'Turn off the volatile when the dressings are on. Emergence carries at least as much risk as induction.',
        'Hand over clearly to recovery staff. The patient remains your responsibility until they are fit for the ward.',
        'Watch as many emergences as you can.',
      ],
      topics: ['e-transfer', 'e-extubation', 'e-pain', 'e-oxygen'] },
  ],
};
